---
---
== Encoding format
ifndef::sourcedir[]
include::common.adoc[]
endif::sourcedir[]

== Intro

This is the description of the Runnel encoding format.

== Prefix common to all fields

Every field has an *index* and a *size*. The *index* is used to lookup the field type from the structure metadata while
the *size* indicates how many bytes the field is made of after the index and size.

|===
|index* |size* |<field specific>
|===

*: Encoded as VLQ (https://en.wikipedia.org/wiki/Variable-length_quantity)

These two are always present, even if the size of some field types is fixed. The reason behind that is because the
structure metadata can change when the data structure changes and may not contain all the indices. When an
index is unknown to the decoder, it can simply skip the field thanks to the guarantee that the field size is always
present.

== Primitive fields

== Bool
|===
|index* |size* |1
|===

Bool always are encoded as one byte.

== Char
|===
|index* |size* |1 |2
|===

Char are UTF-16 characters, 16-bit unsigned.
Bytes are in Big-Endian order.

== Int32
|===
|index* |size* |1 |2 |3 |4
|===

Int32 always are encoded as four bytes.
Bytes are in Big-Endian order.

== Int64
|===
|index* |size* |1 |2 |3 |4 |5 |6 |7 |8
|===

Int64 always are encoded as eight bytes.
Bytes are in Big-Endian order.

== Fp64
|===
|index* |size* |1 |2 |3 |4 |5 |6 |7 |8
|===

Fp64 are IEEE 754 floating-point "double format" bit layout, preserving Not-a-Number
(NaN) values. They always are encoded as eight bytes.
Bytes are in Big-Endian order.

== Enum
|=======
|index* |size* |integer value*
|=======

Enums are encoded as VLQ-encoded integers.

== ByteBuffer
|===
|index* |size* |(bytes) |...
|===

The bytes are just that: plain bytes.

== String
|===
|index* |size* |(bytes) |...
|===

The bytes are the UTF-8-encoded string characters.

== Composite fields

== Array
|===
|index* |size* |length* |entry size* |(entry bytes) |...
|===

The *length* is the array length as is VLQ-encoded.

*entry size* and *entry bytes* actually are the encoded primitive field, minus the index.

== Struct
|===
|index* |size* |field index* |field size* |(field bytes) |...
|===

*field index*, *field size* and *field bytes* actually are the encoded field.
